### ISSUE TITLE
Add ability to download scorecard selections

### ISSUE THREAD

**Issue by balmas** [SUNYORIED/rdaf#4]
Add the ability to download the scorecard selections to a file.  

Still need to figure out what formats that data would be but I think at a minimum:

* a user-friendly report
* an updated dataset including the scores as linked nodes in the graph

**Comment by balmas** [comment]
@Motawala please make these changes:

1.  Capture user selections of the scorecard radio buttons into the global scorecard object
2.  Add a button to export the scorecard as a CSV file with the following columns
Stage ID, Stage Name, Topic ID, Topic Name, Subtopic ID, Subtopic Name, Outcome ID, Outcome Name, Score, Date of Download
3. For score, use the value 0 for Non Started, 1 For In Progress and 2 for Achieved

**Comment by balmas** [comment]
@Motawala this is looking pretty good so far. a few additional requests :

1. could we please provide a default filename for the download? I enter scores.csv and then the .csv got appended, and I think it would be less confusing for people if we just define the filename and download it automatically rather than offering the popup for them to define the name.
2. I would like the download to include ALL of the outcomes, regardless of whether or not they have a score.
3. If the user clicks Download Scores and there isn't anything to download, is it possible to display a message: "You must rate progress on one or more Outcomes in order to download scores".  Alternatively, and probably better, only show the Download Scores and Reset Scores buttons if there are any scores to download or reset?

**Comment by Motawala** [comment]
1. File name is set to Scores.csv.
2. Created an error text message block that appears on the screen if the user clicks on the download or reset button without having the scores on the outcome. Also added the functionality to hide the download button by default, show button when there is any outcomes open on the paper. 
3. Downloads all the open outcomes, if any one or more has the score.
